/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jdbc_emp;

import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EmpManagerGui extends javax.swing.JFrame {
	
	private DeptDAO deptDao;
	private EmpDAO empDao;
	private DefaultTableModel dmodel, emodel; //부서 테이블 모델, 사원 테이블 모델
	String []colHeader1 = {"부서번호","부서명","부서위치"};
	String []colHeader2 = {"사번","사원명","부서번호","부서명","담당업무","입사일"};
    MyMouseEventHandler handler;
    String dnames[];//부서번호 : 부서명 형태의 정보를 저장할 배열
    DefaultComboBoxModel<String> comboModel;
    
    public EmpManagerGui() {
    	super("::EmpManagerGui::");
        initComponents();
        deptDao = new DeptDAO();
        empDao = new EmpDAO();
        tabPane.setSelectedIndex(0);//첫번째 탭을 선택하도록 제어
        tdeptno.setEditable(false);//부서번호 편집 못 하도록
        tempno.setEditable(false);//사번 편집 못 하도록
        thiredate.setEditable(false);//입사일도 수정 못 하게
        
        //부서정보 가져오기
        ArrayList<DeptVO> arr=deptDao.allDept();
        dnames= new String[arr.size()];
        if(arr!=null&&arr.size()>0) {
        	for(int i=0;i<arr.size();i++) {
        		DeptVO dvo = arr.get(i);
        		dnames[i]=dvo.getDeptno()+":"+dvo.getDname();
        	}
        }
        comboModel = new DefaultComboBoxModel(dnames);
        this.cdname.setModel(comboModel);
        
        handler = new MyMouseEventHandler(this);
        tableDept.addMouseListener(handler);
        tableEmp.addMouseListener(handler);;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tdeptno = new javax.swing.JTextField();
        tdname = new javax.swing.JTextField();
        tloc = new javax.swing.JTextField();
        btDlist = new javax.swing.JButton();
        btDadd = new javax.swing.JButton();
        btDdel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDept = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tempno = new javax.swing.JTextField();
        tename = new javax.swing.JTextField();
        tjob = new javax.swing.JTextField();
        thiredate = new javax.swing.JTextField();
        tcomm = new javax.swing.JTextField();
        tsal = new javax.swing.JTextField();
        cdname = new javax.swing.JComboBox();
        btEadd = new javax.swing.JButton();
        btElist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEmp = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btEedit = new javax.swing.JButton();
        btEdel = new javax.swing.JButton();
        btEeditOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("나눔고딕 ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIS 인사 관리 시스템 v1.1");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setText("부서번호");

        jLabel4.setText("부서명");

        jLabel6.setText("부서위치");

        tdeptno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdeptnoActionPerformed(evt);
            }
        });

        btDlist.setText("목 록");
        btDlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDlistActionPerformed(evt);
            }
        });

        btDadd.setText("등 록");
        btDadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDaddActionPerformed(evt);
            }
        });

        btDdel.setText("삭 제");
        btDdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tdeptno, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdname, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tloc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(btDadd)
                .addGap(37, 37, 37)
                .addComponent(btDdel)
                .addGap(40, 40, 40)
                .addComponent(btDlist)
                .addGap(105, 105, 105))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdeptno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tloc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDdel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btDadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableDept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "부서번호", "부서명", "부서위치"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDept);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        tabPane.addTab("부서관리", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel5.setText("담당 업무");

        jLabel7.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel7.setText("부 서 명");

        jLabel8.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel8.setText("입 사 일");

        jLabel9.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel9.setText("사원 이름");

        jLabel10.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel10.setText("보 너 스");

        jLabel11.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel11.setText("급     여");

        jLabel12.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel12.setText("사    번");

        thiredate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thiredateActionPerformed(evt);
            }
        });

        cdname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        cdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdnameActionPerformed(evt);
            }
        });

        btEadd.setText("등    록");
        btEadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEaddActionPerformed(evt);
            }
        });

        btElist.setText("모든 사원 목록");
        btElist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tename, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(tempno)
                        .addComponent(tjob, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(thiredate, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(tsal, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(tcomm, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(cdname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btEadd)
                        .addGap(86, 86, 86)
                        .addComponent(btElist)))
                .addGap(69, 69, 69))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tjob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thiredate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tsal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcomm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btElist)
                    .addComponent(btEadd))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "사번", "사원명", "부서번호", "부서명", "담당업무", "입사일"
            }
        ));
        jScrollPane2.setViewportView(tableEmp);

        btEedit.setText("수   정");
        btEedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEeditActionPerformed(evt);
            }
        });

        btEdel.setText("삭제");
        btEdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdelActionPerformed(evt);
            }
        });

        btEeditOk.setText("수정 처리");
        btEeditOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEeditOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btEedit)
                .addGap(18, 18, 18)
                .addComponent(btEeditOk)
                .addGap(18, 18, 18)
                .addComponent(btEdel)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btEdel, btEedit, btEeditOk});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEedit)
                    .addComponent(btEdel)
                    .addComponent(btEeditOk))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btEdel, btEedit, btEeditOk});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabPane.addTab("인사관리", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdeptnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeptnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdeptnoActionPerformed
    public void showMsg(String message) {
    	JOptionPane.showMessageDialog(this, message);
    }
    private void btDaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDaddActionPerformed
        //1) 사용자가 입력한  부서명, 근무지 얻어오기
    	String dname = tdname.getText();
    	String loc = tloc.getText();
    	//2) 널체크, 빈문자열 체크  - 유효성 체크
    	if(dname.trim().isEmpty()||dname==null||loc==null||loc.trim().isEmpty()) {
    		showMsg("부서명과 부서위치를 입력하세요");
    		tdname.requestFocus();
    		return;
    	}
    	//3) DeptVo객체 생성해서 얻어온 값을 setting
    	DeptVO dvo = new DeptVO();
    	dvo.setDname(dname);
    	dvo.setLoc(loc);
    	//4) deptDao의 insertDept()메소드 호출
    	boolean res = deptDao.insertDept(dvo);
    	//그 결과값에 따른 메시지 처리(등록 성공 or 등록 실패)
    	String message =(res) ? "등록성공":"등록실패";
    	showMsg(message);
    	if(res) {
    		showAllDeptInfo();
    	}
    }//GEN-LAST:event_btDaddActionPerformed
    public void showAllDeptInfo(){
    	ArrayList<DeptVO> dlist = deptDao.allDept();
    	showDeptTable(dlist);
    }
    public void showDeptTable(ArrayList<DeptVO> dlist) {
    	Object [][] data = new Object[dlist.size()][3];//2차원 배열 생성
    	for(int i=0;i<data.length;i++) {
    		DeptVO dept = dlist.get(i);
    		data[i][0]=dept.getDeptno();
    		data[i][1]=dept.getDname();
    		data[i][2]=dept.getLoc();
    	}
    	//부서 테이블 모델
    	dmodel = new DefaultTableModel(data,colHeader1);
    	//뷰와 모델을 연결
    	tableDept.setModel(dmodel);
    }
    private void btDlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDlistActionPerformed
        // 부서정보 보기
    	showAllDeptInfo();
    }//GEN-LAST:event_btDlistActionPerformed

    private void btDdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDdelActionPerformed
    	String deptno = tdeptno.getText();
    	if(deptno==null||deptno.trim().isEmpty()) {
    		showMsg("삭제할 부서를 테이블에서 선택하세요");
    		return;
    	}
    	//삭제의사를 확인
    	int yn = JOptionPane.showConfirmDialog(this, deptno+"를 정말 삭제?","삭제확인",JOptionPane.YES_NO_OPTION);
    	if(yn==JOptionPane.NO_OPTION) {
    		return;
    	}//deptDao의 삭제 처리 메소드 호출
    	boolean sc = deptDao.deleteDept(deptno);
    	//그 실행 결과 메시지 처리(삭제 성공)
    	String message = (sc) ? "삭제성공" : "삭제실패";
    	showMsg(message);
    	//모든 부서정보 가져오기
    	showAllDeptInfo();
    }//GEN-LAST:event_btDdelActionPerformed

    private void thiredateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thiredateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thiredateActionPerformed

    private void cdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdnameActionPerformed

    private void btEaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEaddActionPerformed
    	//1.이름 부서명 업무 급여 보너스 값 받아오기 
    	String ename = this.tename.getText();
    	String dinfo=this.cdname.getSelectedItem().toString();
//    	setTitle(dinfo);
    	String token[]=dinfo.split("\\:");
    	int deptno=Integer.parseInt(token[0]);
    	String dname=token[1];
    	System.out.println(token[0]+" "+token[1]);
    	String job = this.tjob.getText();
    	int sal =Integer.parseInt(this.tsal.getText());
    	int comm =(deptno==30) ? Integer.parseInt(this.tcomm.getText()):0;
    	//2. 유효성 체크 (not null컬럼은 필히 체크)
    	if(ename==null||dinfo==null||ename.trim().isEmpty()||dinfo.trim().isEmpty()) {
    		showMsg("사원명과 부서선택은 필수 입력사항입니다.");
    		tename.requestFocus();
    		return;
    	}
    	//3. 받아온 값으로 EmpVO 객체 생성
    	EmpVO emp = new EmpVO(0,ename,job,0,null,sal,comm,deptno,dname);
    	//4. empDao의 insertEmp()호출
    	boolean result = empDao.insertEmp(emp);
    	//5. 그 실행 결과 메시지 처리
    	String message = (result) ? "사원 정보 등록 성공" : "등록 실패";
    	showMsg(message);
    	showAllEmpInfo();
    }//GEN-LAST:event_btEaddActionPerformed
    public void showAllEmpInfo() {
    	ArrayList<EmpVO> elist = empDao.selectEmpAll();
    	showEmpTable(elist);
    }
    public void showEmpTable(ArrayList<EmpVO> elist) {
    	Object [][] data = new Object[elist.size()][6];//2차원 배열 생성
    	for(int i=0;i<data.length;i++) {
    		EmpVO emp = elist.get(i);
			data[i][0]=emp.getEmpno();
    		data[i][1]=emp.getEname();
    		data[i][2]=emp.getDeptno();
    		data[i][3]=emp.getDname();
    		data[i][4]=emp.getJob();
    		data[i][5]=emp.getHiredate();	
    		
    	}
    	emodel = new DefaultTableModel(data,colHeader2);
    	tableEmp.setModel(emodel);
    }
    private void btElistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElistActionPerformed
    	showAllEmpInfo();
    }//GEN-LAST:event_btElistActionPerformed

    private void btEeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEeditActionPerformed

    private void btEeditOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEeditOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEeditOkActionPerformed

    private void btEdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEdelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpManagerGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDadd;
    private javax.swing.JButton btDdel;
    private javax.swing.JButton btDlist;
    private javax.swing.JButton btEadd;
    private javax.swing.JButton btEdel;
    private javax.swing.JButton btEedit;
    private javax.swing.JButton btEeditOk;
    private javax.swing.JButton btElist;
    private javax.swing.JComboBox cdname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabPane;
     		javax.swing.JTable tableDept;
     		javax.swing.JTable tableEmp;
     		javax.swing.JTextField tcomm;
     		javax.swing.JTextField tdeptno;
     		javax.swing.JTextField tdname;
     		javax.swing.JTextField tempno;
     		javax.swing.JTextField tename;
     		javax.swing.JTextField thiredate;
     		javax.swing.JTextField tjob;
     		javax.swing.JTextField tloc;
     		javax.swing.JTextField tsal;
    // End of variables declaration//GEN-END:variables
}
